---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-nginx-deployment
spec:
    replicas: 1
    selector:
      matchLabels:
          app: nginx
    template:
          metadata:
            labels:
               app: nginx
          spec:
             containers:
               - name: nginx
                 image: k8s.gcr.io/hpa-example
                 resources:
                    reqests:
                      memory: "256Mi"
                      cpu: "500"
                    limits:
                       memory: "500Mi"
                       cpu: "1" 
---
apiVersion: v1
kind: Service
metadata:
   name: my-loadbalancer
spec:
    selector:
       app: nginx
    ports:
     - port: 80
       targetPort: 80
    type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
   name: my-hpa
spec:
  scaleTargertRef:
     apiVersion: apps/v1
     kind: my-nginx-deployment-hpa
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20